//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampiMY701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Spendings
    {
        public int SpendingId { get; set; }
        public string SpendingTitle { get; set; }
        public Nullable<decimal> SpendingAmount { get; set; }
        public Nullable<System.DateTime> SpendingDate { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
