//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpEgitimKampiMY701.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BankProcesses
    {
        public int BankProcessId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ProcessType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Tbl_Banks Tbl_Banks { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
